---
title: "AllCancer_P.1"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

           

```{r, echo = FALSE}
library(reshape)
library(maditr)
#1
Kidney = read.delim('path/to/Kidney/FPKM/Kidney_TumGenExp.txt', header = FALSE, sep = '\t' )
names(Kidney) = c("id", "gene", "exp")
Kidney = dcast(Kidney, id ~ gene, value.var='exp')
Kidney = log(Kidney[,c(2:15)])

#3
Breast = read.table('path/to/Breast/FPKM/Breast_TumGenExp.txt', header = FALSE, sep = '\t' )
names(Breast) = c("id", "gene", "exp")
Breast = dcast(Breast, id ~ gene, value.var='exp')
Breast = log(Breast[,c(2:15)])

#5
Prostate= read.table('path/to/Prostate/FPKM/Prostate_TumGenExp.txt', header = FALSE, sep = '\t' )
#Prostate = log(Prostate)
names(Prostate) = c("id", "gene", "exp")
Prostate = dcast(Prostate, id ~ gene, value.var='exp')
Prostate = log(Prostate[,c(2:15)])

#6
Liver = read.table('path/to/Liver/FPKM/Liver_TumGenExp.txt', header = FALSE, sep = '\t' )
names(Liver) = c("id", "gene", "exp")
Liver = dcast(Liver, id ~ gene, value.var='exp')
Liver = log(Liver[,c(2:15)])

#7
Lung = read.table('path/to/Lung/FPKM/Lung_TumGenExp.txt', header = FALSE, sep = '\t' )
names(Lung) = c("id", "gene", "exp")
Lung = dcast(Lung, id ~ gene, value.var='exp')
Lung = log(Lung[,c(2:15)])

#8
CorpusUteri = read.table('path/to/CorpusUteri/FPKM/CorpusUteri_TumGenExp.txt', header = FALSE, sep = '\t' )
names(CorpusUteri) = c("id", "gene", "exp")
CorpusUteri = dcast(CorpusUteri, id ~ gene, value.var='exp')
CorpusUteri = log(CorpusUteri[,c(2:15)])


library(ggplot2)
library(ggpubr)
library(dplyr)
library(tibble)
library(tidyr)





```


```{r, echo = FALSE}
##APE1->APE2


plotAPE1 = function(the_vars){
  t = deparse(substitute(the_vars))
  ggscatter(the_vars, x= 'APEX1', y = 'APEX2', title = t, shape = 21, color = 'azure4', fill = 'lightcoral', size =2, add = "reg.line", conf.int = TRUE, cor.coef = TRUE, cor.method =  'pearson', ggtheme = theme_gray()) + xlab("APE1") + ylab("APE2")
}

KidneyPlotsAPE1 = plotAPE1(Kidney)
KidneyPlotsAPE1
LungPlotsAPE1 = plotAPE1(Lung)
LungPlotsAPE1
LiverPlotsAPE1 = plotAPE1(Liver)
LiverPlotsAPE1
BreastPlotsAPE1 = plotAPE1(Breast)
BreastPlotsAPE1
CorpusUteriPlotsAPE1 = plotAPE1(CorpusUteri)
CorpusUteriPlotsAPE1
ProstatePlotsAPE1 = plotAPE1(Prostate)
ProstatePlotsAPE1




```

```{r, echo = FALSE}
##BRCA2->APE2


plotBRCA2 = function(the_vars){
  t = deparse(substitute(the_vars))
  ggscatter(the_vars, x= 'BRCA2', y = 'APEX2', title = t, shape = 21, color = 'azure4', fill = 'lightcoral', size =2, add = "reg.line", conf.int = TRUE, cor.coef = TRUE, cor.method =  'pearson', ggtheme = theme_gray()) + ylab("APE2")
}

KidneyPlotsBRCA2 = plotBRCA2(Kidney)
KidneyPlotsBRCA2
LungPlotsBRCA2 = plotBRCA2(Lung)
LungPlotsBRCA2
LiverPlotsBRCA2 = plotBRCA2(Liver)
LiverPlotsBRCA2
BreastPlotsBRCA2 = plotBRCA2(Breast)
BreastPlotsBRCA2
CorpusUteriPlotsBRCA2 = plotBRCA2(CorpusUteri)
CorpusUteriPlotsBRCA2
ProstatePlotsBRCA2 = plotBRCA2(Prostate)
ProstatePlotsBRCA2




```



```{r, echo = FALSE}

##PCNA->APE2

library(ggplot2)
library(ggpubr)
library(dplyr)
library(tibble)
library(tidyr)

plotPCNA = function(the_vars){
  t = deparse(substitute(the_vars))
  ggscatter(the_vars, x = 'PCNA', y = 'APEX2', title = t, shape = 21, color = 'azure4', fill = 'lightcoral', size = 2, add = "reg.line", conf.int = TRUE, cor.coef = TRUE, cor.method = 'pearson', ggtheme = theme_gray()) + ylab("APE2")
}

KidneyPlotsPCNA = plotPCNA(Kidney)
KidneyPlotsPCNA
LungPlotsPCNA = plotPCNA(Lung)
LungPlotsPCNA
LiverPlotsPCNA = plotPCNA(Liver)
LiverPlotsPCNA
BreastPlotsPCNA = plotPCNA(Breast)
BreastPlotsPCNA
CorpusUteriPlotsPCNA = plotPCNA(CorpusUteri)
CorpusUteriPlotsPCNA
ProstatePlotsPCNA = plotPCNA(Prostate)
ProstatePlotsPCNA


```


```{r, echo = FALSE}

##PARP1->APEX2
plotPARP1 = function(the_vars){
  t = deparse(substitute(the_vars))
  ggscatter(the_vars, x= 'PARP1', y = 'APEX2', title = t, shape = 21, color = 'azure4', fill = 'lightcoral', size =2, add = "reg.line", conf.int = TRUE, cor.coef = TRUE, cor.method =  'pearson', ggtheme = theme_gray()) + ylab("APE2")
}

KidneyPlotsPARP1 = plotPARP1(Kidney)
KidneyPlotsPARP1
LungPlotsPARP1 = plotPARP1(Lung)
LungPlotsPARP1
LiverPlotsPARP1 = plotPARP1(Liver)
LiverPlotsPARP1
BreastPlotsPARP1 = plotPARP1(Breast)
BreastPlotsPARP1
CorpusUteriPlotsPARP1 = plotPARP1(CorpusUteri)
CorpusUteriPlotsPARP1
ProstatePlotsPARP1 = plotPARP1(Prostate)
ProstatePlotsPARP1





```

```{r, echo = FALSE}

plotXRCC1 = function(the_vars){
  t = deparse(substitute(the_vars))
  ggscatter(the_vars, x= 'XRCC1', y = 'APEX2', title = t, shape = 21, color = 'azure4', fill = 'lightcoral', size =2, add = "reg.line", conf.int = TRUE, cor.coef = TRUE, cor.method =  'pearson', ggtheme = theme_gray()) + ylab("APE2")
}

KidneyPlotsXRCC1 = plotXRCC1(Kidney)
KidneyPlotsXRCC1
LungPlotsXRCC1 = plotXRCC1(Lung)
LungPlotsXRCC1
LiverPlotsXRCC1 = plotXRCC1(Liver)
LiverPlotsXRCC1
BreastPlotsXRCC1 = plotXRCC1(Breast)
BreastPlotsXRCC1
CorpusUteriPlotsXRCC1 = plotXRCC1(CorpusUteri)
CorpusUteriPlotsXRCC1
ProstatePlotsXRCC1 = plotXRCC1(Prostate)
ProstatePlotsXRCC1

```

```{r, echo = FALSE}
##MRE11->APEX2
plotMRE11 = function(the_vars){
  t = deparse(substitute(the_vars))
  ggscatter(the_vars, x= 'MRE11', y = 'APEX2', title = t, shape = 21, color = 'azure4', fill = 'lightcoral', size =2, add = "reg.line", conf.int = TRUE, cor.coef = TRUE, cor.method =  'pearson', ggtheme = theme_gray()) + ylab("APE2")
}

KidneyPlotsMRE11 = plotMRE11(Kidney)
KidneyPlotsMRE11
LungPlotsMRE11 = plotMRE11(Lung)
LungPlotsMRE11
LiverPlotsMRE11 = plotMRE11(Liver)
LiverPlotsMRE11
BreastPlotsMRE11 = plotMRE11(Breast)
BreastPlotsMRE11
CorpusUteriPlotsMRE11 = plotMRE11(CorpusUteri)
CorpusUteriPlotsMRE11
ProstatePlotsMRE11 = plotMRE11(Prostate)
ProstatePlotsMRE11

```

```{r, echo = FALSE}
##CHEK1->APEX2

plotCHEK1 = function(the_vars){
  t = deparse(substitute(the_vars))
  ggscatter(the_vars, x= 'CHEK1', y = 'APEX2', title = t, shape = 21, color = 'azure4', fill = 'lightcoral', size =2, add = "reg.line", conf.int = TRUE, cor.coef = TRUE, cor.method =  'pearson', ggtheme = theme_gray()) + xlab("CHK1") + ylab("APE2")
}

KidneyPlotsCHEK1 = plotCHEK1(Kidney)
KidneyPlotsCHEK1
LungPlotsCHEK1 = plotCHEK1(Lung)
LungPlotsCHEK1
LiverPlotsCHEK1 = plotCHEK1(Liver)
LiverPlotsCHEK1
BreastPlotsCHEK1 = plotCHEK1(Breast)
BreastPlotsCHEK1
CorpusUteriPlotsCHEK1 = plotCHEK1(CorpusUteri)
CorpusUteriPlotsCHEK1
ProstatePlotsCHEK1 = plotCHEK1(Prostate)
ProstatePlotsCHEK1
```


```{r, echo = FALSE}
##CHEK2->APEX2

plotCHEK2 = function(the_vars){
  t = deparse(substitute(the_vars))
  ggscatter(the_vars, x= 'CHEK2', y = 'APEX2', title = t, shape = 21, color = 'azure4', fill = 'lightcoral', size =2, add = "reg.line", conf.int = TRUE, cor.coef = TRUE, cor.method =  'pearson', ggtheme = theme_gray()) + xlab("CHK2") + ylab("APE2")
}

KidneyPlotsCHEK2 = plotCHEK2(Kidney)
KidneyPlotsCHEK2
LungPlotsCHEK2 = plotCHEK2(Lung)
LungPlotsCHEK2
LiverPlotsCHEK2 = plotCHEK2(Liver)
LiverPlotsCHEK2
BreastPlotsCHEK2 = plotCHEK2(Breast)
BreastPlotsCHEK2
CorpusUteriPlotsCHEK2 = plotCHEK2(CorpusUteri)
CorpusUteriPlotsCHEK2
ProstatePlotsCHEK2 = plotCHEK2(Prostate)
ProstatePlotsCHEK2
```

```{r, echo = FALSE}
##BRCA1->APEX2

plotBRCA1 = function(the_vars){
  t = deparse(substitute(the_vars))
  ggscatter(the_vars, x= 'BRCA1', y = 'APEX2', title = t, shape = 21, color = 'azure4', fill = 'lightcoral', size =2, add = "reg.line", conf.int = TRUE, cor.coef = TRUE, cor.method =  'pearson', ggtheme = theme_gray()) + ylab("APE2")
}

KidneyPlotsBRCA1 = plotBRCA1(Kidney)
KidneyPlotsBRCA1
LungPlotsBRCA1 = plotBRCA1(Lung)
LungPlotsBRCA1
LiverPlotsBRCA1 = plotBRCA1(Liver)
LiverPlotsBRCA1
BreastPlotsBRCA1 = plotBRCA1(Breast)
BreastPlotsBRCA1
CorpusUteriPlotsBRCA1 = plotBRCA1(CorpusUteri)
CorpusUteriPlotsBRCA1
ProstatePlotsBRCA1 = plotBRCA1(Prostate)
ProstatePlotsBRCA1
```


```{r, echo = FALSE}
##TOPBP1->APEX2

plotTOPBP1 = function(the_vars){
  t = deparse(substitute(the_vars))
  ggscatter(the_vars, x= 'TOPBP1', y = 'APEX2', title = t, shape = 21, color = 'azure4', fill = 'lightcoral', size =2, add = "reg.line", conf.int = TRUE, cor.coef = TRUE, cor.method =  'pearson', ggtheme = theme_gray()) + ylab("APE2")
}

KidneyPlotsTOPBP1 = plotTOPBP1(Kidney)
KidneyPlotsTOPBP1
LungPlotsTOPBP1 = plotTOPBP1(Lung)
LungPlotsTOPBP1
LiverPlotsTOPBP1 = plotTOPBP1(Liver)
LiverPlotsTOPBP1
BreastPlotsTOPBP1 = plotTOPBP1(Breast)
BreastPlotsTOPBP1
CorpusUteriPlotsTOPBP1 = plotTOPBP1(CorpusUteri)
CorpusUteriPlotsTOPBP1
ProstatePlotsTOPBP1 = plotTOPBP1(Prostate)
ProstatePlotsTOPBP1
```


```{r, echo = FALSE}
##ATM->APEX2

plotATM = function(the_vars){
  t = deparse(substitute(the_vars))
  ggscatter(the_vars, x = 'ATM', y = 'APEX2', title = t, shape = 21, color = 'azure4', fill = 'lightcoral', size =2, add = "reg.line", conf.int = TRUE, cor.coef = TRUE, cor.method =  'pearson', ggtheme = theme_gray()) + ylab("APE2")
}

KidneyPlotsATM = plotATM(Kidney)
KidneyPlotsATM
LungPlotsATM = plotATM(Lung)
LungPlotsATM
LiverPlotsATM = plotATM(Liver)
LiverPlotsATM
BreastPlotsATM = plotATM(Breast)
BreastPlotsATM
CorpusUteriPlotsATM = plotATM(CorpusUteri)
CorpusUteriPlotsATM
ProstatePlotsATM = plotATM(Prostate)
ProstatePlotsATM
```

```{r, echo = FALSE}
##ATR->APEX2

plotATR = function(the_vars){
  t = deparse(substitute(the_vars))
  ggscatter(the_vars, x= 'ATR', y = 'APEX2', title = t, shape = 21, color = 'azure4', fill = 'lightcoral', size =2, add = "reg.line", conf.int = TRUE, cor.coef = TRUE, cor.method =  'pearson', ggtheme = theme_gray()) + ylab("APE2")
}

KidneyPlotsATR = plotATR(Kidney)
KidneyPlotsATR
LungPlotsATR = plotATR(Lung)
LungPlotsATR
LiverPlotsATR = plotATR(Liver)
LiverPlotsATR
BreastPlotsATR = plotATR(Breast)
BreastPlotsATR
CorpusUteriPlotsATR = plotATR(CorpusUteri)
CorpusUteriPlotsATR
ProstatePlotsATR = plotATR(Prostate)
ProstatePlotsATR
```


```{r, echo = FALSE}
##RAD50->APEX2

plotRAD50 = function(the_vars){
  t = deparse(substitute(the_vars))
  ggscatter(the_vars, x= 'RAD50', y = 'APEX2', title = t, shape = 21, color = 'azure4', fill = 'lightcoral', size =2, add = "reg.line", conf.int = TRUE, cor.coef = TRUE, cor.method =  'pearson', ggtheme = theme_gray()) + ylab('APE2')
}

KidneyPlotsRAD50 = plotRAD50(Kidney)
KidneyPlotsRAD50
LungPlotsRAD50 = plotRAD50(Lung)
LungPlotsRAD50
LiverPlotsRAD50 = plotRAD50(Liver)
LiverPlotsRAD50
BreastPlotsRAD50 = plotRAD50(Breast)
BreastPlotsRAD50
CorpusUteriPlotsRAD50 = plotRAD50(CorpusUteri)
CorpusUteriPlotsRAD50
ProstatePlotsRAD50 = plotRAD50(Prostate)
ProstatePlotsRAD50
```

