---
title: "Lolliplot"
author: "Katie Jensen"
date: "September 28, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(ggplot2)
library(ggrepel)

#labely = 
Can = read.table("C://path/to/cancerMutes.txt", header = TRUE, sep = '\t')

snv = Can$cancer

x = ggplot(data=Can, aes(AA_position, Count)) + theme_bw() + theme(panel.background = element_blank(), panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.border = element_blank(), axis.title.y = element_blank(), axis.text.y = element_blank()) + coord_fixed(35) + ylab("Count across\nsamples") + scale_y_continuous(limit = c(-1, 4)) + scale_x_continuous(limit = c(-20, 560)) + geom_point() +
geom_text_repel(data = Can, size = 1.5, nudge_y = 1,nudge_x = .1,   aes(x = AA_position, y = Count, label = snv,angle = 90)) 

x
```

```{r}

#if (!requireNamespace("BiocManager", quietly = TRUE))
#  install.packages("BiocManager")

#BiocManager::install("GenVisR")
```
```{r}
#library(GenVisR)
#library(curl)
#if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

#BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")
#library(BSgenome.Hsapiens.UCSC.hg19)
#BSgenome <- BSgenome.Hsapiens.UCSC.hg19

#lolliplot(L)
#dev.off()
```
```{r}
#geom_segment( aes(AA_position, xend=AA_position, y=0, yend = Count), colour="#660099") + geom_segment( aes(x = AA_position, xend = AA_position, yend = .5, y = Count, label = snv )) + 
```


